### PR TITLE
Run all "check" tasks

### PR DESCRIPTION
**Pull request by knittl**
Run all "check" tasks

Depend on the `check` Lifecycle Task to execute all default and
user-defined verification tasks. The new default behavior is to run
`check`. Users can set `GRADLE_TESTPACK_LEGACY_TASK` to any non-empty
value to restore the old behavior of running only the `test` task.

The [Gradle Java Plugin][1] defines a task hierarchy, with the `build`
task at the top which executes all other tasks. Test tasks are split
into the top level task `check` which depends on `test`.

> **check**
>
> Depends on: `test`
>
> Aggregate task that performs verification tasks, such as running the
> tests. Some plugins add their own verification tasks to check. You
> should also attach any custom Test tasks to this lifecycle task if you
> want them to execute for a full build. This task is added by the Base
> Plugin.

Often it is useful to split unit tests and integration tests into
distinct source sets and tasks. The [canonical example][2] from the
Gradle docs links this new test task to the `check` top level task.

[1]: https://docs.gradle.org/current/userguide/java_plugin.html
[2]: https://docs.gradle.org/current/userguide/java_testing.html#sec:configuring_java_integration_tests

### CODE REVIEW

**Comment by Malax** [comment]
Hi there, thanks for the PR! I'm in favor of making this change. However, here are some things to consider:

Some users might depend on the fact this only runs `test` and not `check`. This will be a breaking change for those users. Since users usually get the new version of the buildpack automatically it will break out of nowhere. Even though I think the percentage of affected users is close to zero, we need an escape hatch for them to restore the previous behavior easily.

I'm thinking of a new boolean-ish environment variable (`GRADLE_TESTPACK_LEGACY_TASK`?) that will enable the old behavior. Do you want to take a stab implementing this?

Open tasks from Heroku's side:
- [ ] Release new buildpack version
- [ ] Update Heroku CI docs: https://devcenter.heroku.com/articles/heroku-ci#gradle
- [ ] Issue a Changelog Entry: https://devcenter.heroku.com/changelog

**Comment by knittl** [comment]
@Malax of course, makes sense. I have updated the PR to include a new var (`GRADLE_TESTPACK_LEGACY_TASK`) to restore old behavior.

But I wonder if instead of a bool-ish control variable, we should rather allow users to override the verification task with any value they want, similar to lines 45-47 in `bin/compile`:

```sh
if [ -z "$GRADLE_TASK" ]; then
  GRADLE_TASK="${DEFAULT_GRADLE_TASK}"
fi
```

Maybe we could introduce a new var `GRADLE_CHECK_TASK` (suggestions welcome … `GRADLE_TEST_TASK`, `GRADLE_VERIFICATION_TASK`?) which defaults to `check`, but users can override it to be `test` instead (or `my_custom_test_task`).

WDYT?

**Comment by Malax** [comment]
This looks great! Thank you! 

I'm hesitant to add the ability to set your own task directly. I'd like this to still be opinionated as the rest of the platform and testpacks are. I plan to remove `GRADLE_TESTPACK_LEGACY_TASK` after some time has passed too - it's really just meant to temporarily help folks that might be affected by the change to `check`.

I ran CI against your branch and there are some tests that fail because they specifically check for `test` task exclusions. I'll fix those. I think we can ship this very soon.

**Review by Malax — APPROVED** [review]

**Comment by Malax** [comment]
This has been released as `v34`.

**Pull request merged**
